### PR TITLE
Initial version of SliverTabView

### PR DESCRIPTION
**Pull request by Kavantix**
**NOT FINISHED!**

Example usage: 

```dart
class MyHomePage extends StatefulWidget {
  const MyHomePage({Key? key, required this.title}) : super(key: key);

  final String title;

  @override
  State<MyHomePage> createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage>
    with SingleTickerProviderStateMixin {
  late final _horizontalController = TabController(length: 3, vsync: this);

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.title),
      ),
      body: CustomScrollView(
        slivers: [
          MultiSliver(
            children: [
              SliverPinnedHeader(
                child: Container(
                  color: Colors.white,
                  child: TabBar(
                    controller: _horizontalController,
                    tabs: const [
                      Tab(text: 'Red'),
                      Tab(text: 'Blue'),
                      Tab(text: 'Green'),
                    ],
                    labelColor: Colors.black,
                  ),
                ),
              ),
              SliverTabView(
                precedingPinnedExtent: 48,
                children: [
                  SliverToBoxAdapter(
                    child: Container(
                      height: 2000,
                      color: Colors.red,
                      child: Placeholder(),
                    ),
                  ),
                  SliverToBoxAdapter(
                    child: Container(
                      height: 10000,
                      color: Colors.blue,
                      child: Placeholder(),
                    ),
                  ),
                  SliverToBoxAdapter(
                    child: Container(
                      height: 1000,
                      color: Colors.green,
                      child: Placeholder(),
                    ),
                  ),
                ],
                horizontalController: _horizontalController,
              ),
            ],
          ),
        ],
      ),
    );
  }
}

```

### CODE REVIEW

**Comment by Kavantix** [comment]
@MindMayhem you can check this one out. I'm curious what you think of it.

**Comment by Kavantix** [comment]
Note that I edited the example a bit to add a tab bar

**Comment by arxdeus** [comment]
> @MindMayhem you can check this one out. I'm curious what you think of it.

Checked out it, seems like it works similar to SliverIndexedStack, but it using TabController for control, instead directly providing index

Honestly, i don't see difference between SliverIndexStack and SliverTabView
Sometimes using ValueNotifier will be more lightweight than using complex TabController with TickerProvider (which, for sure, doesn't used here)

**Comment by Kavantix** [comment]
@MindMayhem it is used, this tabview is animated and draggable and maintains the scroll state seperatly for the tabs

**Comment by EArminjon** [comment]
@Kavantix  any update <3 ?

**Comment by EArminjon** [comment]
```dart
class Test extends StatefulWidget {
  const Test({super.key});

  static const String routeName = "catalog_choice_page";

  @override
  State<Test> createState() => _TestState();
}

class _TestState extends State<Test> with SingleTickerProviderStateMixin {
  late final TabController tabController;

  @override
  void initState() {
    super.initState();

    tabController = TabController(length: 2, vsync: this);
  }

  @override
  void dispose() {
    super.dispose();

    tabController.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return CustomScrollView(
      physics: const ClampingScrollPhysics(),
      slivers: <Widget>[
        SliverToBoxAdapter(
          child: Container(
            padding: const EdgeInsets.all(30),
            color: Colors.blue,
          ),
        ),
        SliverToBoxAdapter(
          child: Container(
            padding: const EdgeInsets.all(30),
            color: Colors.green,
          ),
        ),
        SliverToBoxAdapter(
          child: TabBar(
            controller: tabController,
            tabs: const <Widget>[
              Tab(text: "tab 1"),
              Tab(text: "tab 2"),
            ],
          ),
        ),
        SliverTabView(
          horizontalController: tabController,
          children: const <Widget>[
            SliverToBoxAdapter(
              child: Center(child: Text("Page 1")),
            ),
            SliverToBoxAdapter(
              child: Center(child: Text("Page 2")),
            ),
          ],
        ),
      ],
    );
  }
}
```


View is scrollable but it maybe should not because of the physics chosen in CustomScrollView(). 
By removing the SliverTabView(), the view is well not scrollable.

**Comment by Kavantix** [comment]
Hi @EArminjon I am not really planning on continuing this PR anytime soon as I currently have no need for this and didn't really hear from others.

**Comment by EArminjon** [comment]
Oh sad, need it for a complex UI with multiple TabbarView.

**Pull request closed without merging**
