### PR TITLE
Fix RenderMultiSliver SliverGeometry.maxScrollObstructionExtent

### LINKED ISSUE #56: MultiSliver with several pinned headers in NestScrollView headerSliverBuilder need overscrolling to overlap
When I put MultiSliver in `NestedScrollView.headerSliverBuilder` with several pinned headers inside, I need to "overscroll" to begin overlapping the body. The problem doesn't occur with one pinned header.

In the demo, look at the cursor and the shadow beneath the TabBar.

demo

The code :

```dart
import 'package:flutter/material.dart';
import 'package:sliver_tools/sliver_tools.dart';

void main() {
  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({Key? key}) : super(key: key);

  static const String _title = 'Flutter Code Sample';

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      title: _title,
      home: MyStatelessWidget(),
    );
  }
}

class MyStatelessWidget extends StatelessWidget {
  const MyStatelessWidget({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    final List<String> tabs = <String>['Tab 1', 'Tab 2'];
    return DefaultTabController(
      length: tabs.length, // This is the number of tabs.
      child: Scaffold(
        body: NestedScrollView(
          headerSliverBuilder: (BuildContext context, bool innerBoxIsScrolled) {
            return <Widget>[
              SliverOverlapAbsorber(
                handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                sliver: MediaQuery.removePadding(
                  context: context,
                  removeBottom: true,
                  child: MultiSliver(
                    children: [
                      const SliverPinnedHeader(
                          child: SafeArea(child: Padding(padding: EdgeInsets.all(16), child: Text('Test')))),
                      SliverAppBar(
                        title: const Text('Books'), // This is the title in the app bar.
                        pinned: true,
                        expandedHeight: 150.0,
                        forceElevated: innerBoxIsScrolled,
                        bottom: TabBar(
                          tabs: tabs.map((String name) => Tab(text: name)).toList(),
                        ),
                      ),
                    ],
                  ),
                ),
              ),
            ];
          },
          body: TabBarView(
            // These are the contents of the tab views, below the tabs.
            children: tabs.map((String name) {
              return SafeArea(
                top: false,
                bottom: false,
                child: Builder(
                  builder: (BuildContext context) {
                    return CustomScrollView(
                      key: PageStorageKey<String>(name),
                      slivers: <Widget>[
                        SliverOverlapInjector(
                          // This is the flip side of the SliverOverlapAbsorber
                          // above.
                          handle: NestedScrollView.sliverOverlapAbsorberHandleFor(context),
                        ),
                        SliverPadding(
                          padding: const EdgeInsets.all(8.0),
                          sliver: SliverFixedExtentList(
                            itemExtent: 48.0,
                            delegate: SliverChildBuilderDelegate(
                              (BuildContext context, int index) {
                                return ListTile(
                                  title: Text('Item $index'),
                                );
                              },
                              childCount: 30,
                            ),
                          ),
                        ),
                      ],
                    );
                  },
                ),
              );
            }).toList(),
          ),
        ),
      ),
    );
  }
}
```

The problem is also on iOS and Web.

Flutter doctor :

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.0.4, on macOS 12.5 21G72 darwin-arm, locale fr-FR)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.2)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.1.3)
[✓] VS Code (version 1.70.0)
[✓] Connected device (3 available)
[✓] HTTP Host Availability
```

Thanks for your help.

### PR DESCRIPTION
**Pull request by manu-sncf**
PR to fix #56

### CODE REVIEW

**Comment by Kavantix** [comment]
Thanks for the PR!, I believe the += is indeed correct.
But we should be able to make a simpler test case for this that does not rely on the nestedscrollview, do you have time to change the testcase?

**Comment by manu-sncf** [comment]
I looked in flutter source code where `maxScrollObstructionExtent` is used : 
* `RenderViewPortBase.getOffsetToReveal`: "Returns the offset that would be needed to reveal the target [RenderObject]." (which is used by `Scrollable.ensureVisible` for example)
* And `NestedScrollView`

So I can implement a `Scrollable.ensureVisible` use case but i'm not sure if it is simpler.

Or in the actual test of the PR, I can suppress the `TabBarView` which is a little bit simpler.

What do you think ?

**Comment by Kavantix** [comment]
I was thinking more in the line of calling layout manually and checking the value in the geometry

**Comment by Kavantix** [comment]
For instance provide the multisliver with 2 pinned headers (so no nested scrollview required)

**Comment by manu-sncf** [comment]
OK, I think it can work for the test, but keep in mind this case works perfectly with scrolls when manually testing.

**Comment by manu-sncf** [comment]
The test simplified has been pushed.

**Comment by Kavantix** [comment]
Thanks for making the effort!
I would suggest just 1 improvement.
The test widget class you created is quite simple and only used once.
So you can simply put the content of the build method into the pumpwidget call directly so we dont need the separate file

**Comment by manu-sncf** [comment]
Done :-) !

**Comment by Kavantix** [comment]
Thanks for the contribution @manu-sncf!

**Comment by Kavantix** [comment]
Published it as 0.2.8

**Pull request merged**
