### PR TITLE
SliverIndexedStack

### LINKED ISSUE #36: SliverIndexedStack
Hi Pieter,

Thank you for an amazing plugin. Is it possible to add SliverIndexedStack that works like an IndexedStack but accepts Slivers.

Best,
Shashi

### PR DESCRIPTION
**Pull request by Kavantix**
Closes #36

### CODE REVIEW

**Comment by Kavantix** [comment]
Needs tests

**Comment by ChauCM** [comment]
Tried it and get empty pages.

something like this
```
CustomScrollView(
          controller: scrollController,
          slivers: [
            SliverIndexedStack(
              index: 1,
              children: [
                const SliverToBoxAdapter(child: Text('content2')),
                const SliverToBoxAdapter(child: Text('content1')),
              ],
            ),
          ],
        );
```

**Comment by Kavantix** [comment]
Thanks for testing @ChauCM, I'll have a look at what's wrong

**Comment by arxdeus** [comment]
HI, any progress here? Same problem with no content

**Comment by Kavantix** [comment]
@MindMayhem @ChauCM I finally had some time to write a few tests and fix the issue. Can you test if it works like expected now.

**Comment by Kavantix** [comment]
@MindMayhem can you share a minimal example

**Comment by arxdeus** [comment]
> @MindMayhem can you share a minimal example

Sorry, it was my problem (wrong branch, lul), everything fine!

Will u add lazy load and animation features for this?

**Comment by Kavantix** [comment]
Not sure to be honest.
This behavior is the same as the normal IndexedStack but I’m not sure it makes sense for slivers.
For the current behavior lazy loading is not possible though since all children need to be layed out

**Comment by Kavantix** [comment]
@MindMayhem what is your usecase for this widget?
I’m thinking about how much sense this widget even makes and what it exactly adds to the package that isn’t already covered by other widgets

**Comment by arxdeus** [comment]
> @MindMayhem what is your usecase for this widget? I’m thinking about how much sense this widget even makes and what it exactly adds to the package that isn’t already covered by other widgets

In my case i have CustomScrollView with inner tabs which contains different widgets, but i doesn't want to rebuild it everytime when i switch tab (before i used ValueListenableBuilder in CustomScrollView for "switching tabs", but it always rebuilds whole widgets and doesn't save state)
Also, i can't use TabView here, because of design

So, SliverIndexedStack comes really helpfull for me, glad to see you made this

**Comment by Kavantix** [comment]
@MindMayhem for that usecase I probably have something better in a private repo of mine. Perhaps it makes more sense to put that one in this package 🤔
I’ll see if I can share it in a different draft PR in a few hours

**Comment by MindMayhem** [comment]
hey, is it possible to implement animation support?

**Comment by kamami** [comment]
I have the same use case as [hot-moms](https://github.com/hot-moms). How did you solve this?

**Pull request closed without merging**
